package com.squad10.chatboteasy.enums;

public enum EtapaFluxo {
    INICIO,
    MENU_PRINCIPAL,
    RESUMO_MES,
    CONTAS_RECEBER_TIPO,
    CONTAS_RECEBER_LISTA,
    CONTAS_PAGAR_TIPO,
    CONTAS_PAGAR_LISTA,
    FLUXO_CAIXA_PERIODO,
    RELATORIO_ESCOLHER_PERIODO,
    RELATORIO_AGUARDANDO_DATAS,
    REPETIR,
    SAIR
}
